#ifndef MONITOR_DEF_H
#define MONITOR_DEF_H

#define MONITOR_BUFFER_SIZE 32768
#define MONITOR_MAX_ARG_LEN 40
#define MONITOR_MAX_CMD_LEN 40

enum monitor_error_codes {
        MONITOR_NO_ERROR = 0,
        MONITOR_INVALID_CHAR,
        MONITOR_INVALID_CMD,
        MONITOR_INVALID_ARG,
        MONITOR_NOT_LOGGED,
        MONITOR_WRONG_LOGIN,
        MONITOR_INVALID_USER,
        MONITOR_ALREADY_LOGGED,
        MONITOR_NOT_USER_LIST,
        MONITOR_FULL_USERS,
        MONITOR_USER_EXISTS,
        MONITOR_USER_ONLINE,
        MONITOR_CANT_CREATE_MAILDIR,
        MONITOR_CANT_RM_MAILDIR,
        MONITOR_CMD_ERROR,
        MONITOR_UNKNOWN_ERROR
};

#endif // !MONITOR_DEF_H
